### PR TITLE
Serialization, integration tests and travis

### PR DESCRIPTION
**Pull request by ghost**
Hello Brian

I created integration tests for zmqweb and added all the travis metadata. This pull request also contains the change to msgpack (I also updated setup.py here). If json will be kept, I'll create a new pull request or update this accordingly.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Hi, this is great!  I am travelling this week and next, but I will try to review this soon.  One short thought - we probably want to make the serialization format extensible, so that users can pick JSON or msgpack or even pickle if needed.  We have also done this with zpyrpc:

https://github.com/ellisonbg/zpyrpc/blob/master/zpyrpc/serializer.py

**Comment by ghost** [comment]
Great plan, I will implement that on this branch, but it might take a few days.

**Comment by ghost** [comment]
Because of this behavior:

``` python
In [7] (~): msgpack.loads(msgpack.dumps(b"huhu", encoding='utf-8'), encoding='utf-8')
    Out[7]: 'huhu'

In [8] (~): msgpack.loads(msgpack.dumps("huhu", encoding='utf-8'), encoding='utf-8')
    Out[8]: 'huhu'

In [9] (~): msgpack.loads(msgpack.dumps(b"huhu", encoding=None), encoding=None)
    Out[9]: b'huhu'

In [10] (~): msgpack.loads(msgpack.dumps("huhu", encoding=None), encoding=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-9966bea0f7e5> in <module>()
----> 1 msgpack.loads(msgpack.dumps("huhu", encoding=None), encoding=None)

.....

TypeError: Can't encode unicode string: no encoding is specified
```

It is imo necessary to handle the decision if string is binary or not explicitly in zmqweb.

Related discussion: https://github.com/msgpack/msgpack/issues/121

**Comment by ghost** [comment]
I got a bit carried away, by travis problems I didn't understand then. It's now all mixed in this branch. I close this for now and start a new pull-request once I got it solved properly.

**Pull request closed without merging**
