### PR TITLE
Python 3 problems

### PR DESCRIPTION
**Pull request by ghost**
Hello Brian

I have two problems when using zmqweb with python3. I fixed one in the pull request.

The second can be triggered with this url: http://localhost:8888/foo/sleep?t=1

The parameter t will be binary ie b'1', json can't serialize this. I'm not sure how to fix this. I doubt that json is the right tool to encode this messages, since the http body can be binary anyways. My first idea was to replace json with MessagePack, pickle or bson, I suppose since you use zmq everyday you know a better solution.

Jean-Louis

### CODE REVIEW

**Comment by ghost** [comment]
The traceback:

``` python

ERROR:root:Unexpected error in _execute
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/zmqweb-0.1-py3.2.egg/zmqweb/proxy.py", line 239, in _execute
    self.request, args, kwargs, self, self.timeout
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/zmqweb-0.1-py3.2.egg/zmqweb/proxy.py", line 92, in send_request
    msg_list = [b'|', msg_id, jsonapi.dumps(req)]
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/zmq/utils/jsonapi.py", line 72, in dumps
    return _squash_unicode(jsonmod.dumps(o, **kwargs))
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/json/__init__.py", line 233, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/json/encoder.py", line 188, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/json/encoder.py", line 246, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.2.3/Frameworks/Python.framework/Versions/3.2/lib/python3.2/json/encoder.py", line 170, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'1' is not JSON serializable
```

**Comment by ghost** [comment]
I replaced json with msgpack as a proposal. (see first message)

**Comment by ellisonbg** [comment]
I think you are right that msgpack is probably a better default, but this should be extensible...

**Comment by ghost** [comment]
Great plan. I will continue in this pull request: https://github.com/ellisonbg/zmqweb/pull/2

**Pull request closed without merging**
